### PR TITLE
Add Rspec spec on controllers

### PR DESCRIPTION
**Pull request by AlierPM**
- [x] Added RSpec as a gem to your project.
- [x] Created a Request spec file for all your controllers.
- [x] Made sure that each action I check:
     * If the response status was correct.
     * If a correct template was rendered.
     * If the response body includes the correct placeholder text.

### CODE REVIEW

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @AlierPM       :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

**Kindly do not make it a habit of opening new pull requests in an attempt to not make the changes requested. The next reviewer will still require to make the changes regardless of whether you open a new PR so long as the changes requested were not made.**

- [x] As you were requested by the previous reviewers, you need to include and install the rspec gem in your Gemfile.  Kindly include it and resolve the errors.
- [x] I am also getting the same errors when running rspec as the previous reviewers because rspec is not itself included in the gemfile. Kindly include it and resolve the errors.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlierPM** [comment]
@Nemwel-Boniface; could you please elaborate on the changes on the zoom call? Everything is passing on my side

**Comment by AlierPM** [comment]
@Nemwel-Boniface The project is running well and tests passing on my side.

**Review by AnselemOdims — CHANGES_REQUESTED** [review]
### Hi @AlierPM , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] As pointed out by the previous reviewers, please kindly include the rspec gem in your Gemfile 

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AlierPM** [comment]
@AnselemOdims; could you mind a zoom call, please?

**Review by Davidosky007 — APPROVED** [review]
Hi @AlierPM 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sinansevgi — COMMENTED** [review]
Hello @AlierPM 👋,

_This is an additional review as a result of the second opinion request._

I see that the code has already been reviewed and approved. If there are no further issues, it looks like the PR is ready to be merged. Let me know if there is anything else I can assist with.

Keep rocking 🚀!

**Pull request merged**
